Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace StockApp.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ItemController(ApplicationDbContext context)
        {
            _context = context;
        }

        // Get : All Items
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var items = await _context.Items
                .Include(i => i.Store) 
                .ToListAsync();

            var itemViewModels = items.Select(i => new ItemViewModel
            {
                Id = i.ItemId,
                Name = i.Name,
                StoreId = i.StoreId,
                Stores = _context.Stores.ToList() 
            });

            return View(itemViewModels);
        }

        // Get : Create Form
        [HttpGet]
        public IActionResult Create()
        {
            var model = new ItemViewModel
            {
                Stores = _context.Stores.ToList()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ItemViewModel model)
        {
            if (ModelState.IsValid)
            {
                var item = new Item
                {
                    Name = model.Name,
                    StoreId = model.StoreId
                };

                _context.Items.Add(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            model.Stores = _context.Stores.ToList();
            return View(model);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items.FindAsync(id);

            if (item == null)
            {
                return NotFound();
            }

            var model = new ItemViewModel
            {
                Id = item.ItemId,
                Name = item.Name,
                StoreId = item.StoreId,
                Stores = await _context.Stores.ToListAsync()
            };

            return View(model);
        }

        // POST: Item/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ItemViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var item = new Item
                {
                    ItemId = model.Id,
                    Name = model.Name,
                    StoreId = model.StoreId
                };

                _context.Entry(item).State = EntityState.Modified;
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index)); 
            }

            model.Stores = await _context.Stores.ToListAsync();
            return View(model);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();

            var item = await _context.Items.FindAsync(id);

            if (item == null)
                return NotFound();

            _context.Items.Remove(item);
            _context.SaveChanges();

            return Ok();
        }





    }
}

Controllers/StoreController.cs
namespace StockApp.Controllers
{

    public class StoreController : Controller
    {
        private readonly ApplicationDbContext _context;
       

        public StoreController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GETAll: Store 
        public IActionResult Index()
        {
            var model = _context.Stores
                .Select(s => new StoreViewModel
                {
                    StoreId = s.StoreId,
                    Name = s.Name,
                    Items = s.Items.ToList()
                })
                .ToList();

            return View(model);
        }



        // GET: Store/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Store/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StoreViewModel model)
        {
            if (ModelState.IsValid)
            {
                var store = new Store
                {
                    Name = model.Name
                };

                _context.Stores.Add(store);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }




        // GET: Store/Edit/ID
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var store = await _context.Stores.FindAsync(id);

            if (store == null)
            {
                return NotFound();
            }

            var storeViewModel = new StoreViewModel
            {
                StoreId = store.StoreId,
                Name = store.Name,
                Items = store.Items.ToList()
            };

            return View(storeViewModel);
        }

        // POST: Store/Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, StoreViewModel model)
        {
            if (id != model.StoreId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var store = new Store
                    {
                        StoreId = model.StoreId,
                        Name = model.Name
                    };

                    _context.Stores.Update(store);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StoreExists(model.StoreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();

            var store = await _context.Stores.FindAsync(id);

            if (store == null)
                return NotFound();

            _context.Stores.Remove(store);
            _context.SaveChanges();

            return Ok();
        }

        public bool StoreExists(int id)
        {
            return _context.Stores.Any(e => e.StoreId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StockApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StockApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Item</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Store</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - StockApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>